# services:
#   - type: web
#     name: backend
#     env: node
#     plan: free
#     buildCommand: "cd backend && npm install"
#     startCommand: "node backend/app.js"
#     envVars:
#       - key: PATH
#         value: "/opt/render/project/src/.venv/bin:$PATH"

#   - type: web
#     name: python-scripts
#     env: python
#     plan: free
#     buildCommand: "pip install -r scripts/requirements.txt"
#     startCommand: "cd scripts && python script.py"
#     envVars:
#       - key: PATH
#         value: "/opt/render/project/src/.venv/bin:$PATH"
# #---------------------------------


# services:
#   - type: web
#     name: node-backend
#     env: node
#     plan: free
#     buildCommand: " npm install && apt-get update && apt-get install -y ffmpeg"
#     startCommand: "node app.js"
#     envVars:
#       - key: PATH
#         value: "/usr/bin/ffmpeg:$PATH"

#   - type: web
#     name: python-scripts
#     env: python
#     plan: free
#     buildCommand: "pip install -r scripts/requirements.txt && apt-get update && apt-get install -y ffmpeg"
#     startCommand: "cd scripts && python script.py"
#     envVars:
#       - key: PATH
#         value: "/usr/bin/ffmpeg:$PATH"services:services:

services:
  - type: web
    name: node-backend
    env: node
    plan: free
    buildCommand: "npm install && apt-get update && apt-get install -y ffmpeg"
    startCommand: "node app.js"
    envVars:
      - key: PATH
        value: "/usr/bin/ffmpeg:$PATH"
      - key: PORT
        value: "5000"
        
  - type: web
    name: python-scripts
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && apt-get update && apt-get install -y ffmpeg"
    startCommand: "flask run --host=0.0.0.0 --port 5001"
    envVars:
      - key: PATH
        value: "/usr/bin/ffmpeg:$PATH"
      - key: FLASK_APP
        value: "app.py"
      - key: FLASK_ENV
        value: "production"
      - key: PORT
        value: "5001"
