services:
  - type: web
    name: node-backend
    env: node
    plan: free
    buildCommand: "npm install && apt-get update && apt-get install -y ffmpeg"
    startCommand: "node app.js"
    envVars:
      - key: PATH
        value: "/usr/bin/ffmpeg:$PATH"
        
  - type: web
    name: python-scripts
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && apt-get update && apt-get install -y ffmpeg"
    startCommand: "flask run --host=0.0.0.0 --port $PORT"
    envVars:
      - key: PATH
        value: "/usr/bin/ffmpeg:$PATH"
      - key: FLASK_APP
        value: "app.py"
      - key: FLASK_ENV
        value: "production"
